#!/bin/bash
# Regenerates packages/rewamp_audio/src/sid_filter_maps.h from sidplayfp's
# player.cpp (the console player, github.com/libsidplayfp/sidplayfp) — the
# author→filter recommendation tables used by its --autofilter mode.
#
#   ./scripts/sync_sidplayfp_filtermaps.sh [ref]        # default: master
#   ./scripts/sync_sidplayfp_filtermaps.sh /path/to/player.cpp
#
# Idempotent; run it to pick up upstream table updates.
set -euo pipefail
cd "$(dirname "$0")/.."

REF="${1:-master}"
OUT="src/sid_filter_maps.h"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if [ -f "$REF" ]; then
  cp "$REF" "$TMP"
  SRC="$REF"
else
  URL="https://raw.githubusercontent.com/libsidplayfp/sidplayfp/$REF/src/player.cpp"
  curl -fsSL "$URL" -o "$TMP"
  SRC="$URL"
fi

python3 - "$TMP" "$OUT" "$SRC" <<'PY'
import re, sys
src, out, origin = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(src, encoding='latin-1').read()

def extract(name):
    m = re.search(r'filter_map_t\s+' + name + r'\s*=\s*\{(.*?)\n\};', text, re.S)
    if not m:
        sys.exit(f'table {name} not found in {origin}')
    entries = re.findall(r'\{\s*"((?:[^"\\]|\\.)*)"\s*,\s*([0-9.]+)\s*\}', m.group(1))
    if not entries:
        sys.exit(f'table {name} empty')
    return entries

ranges = extract('filterRangeMap')
curves = extract('filterCurveMap')

with open(out, 'w', encoding='utf-8') as f:
    f.write('/* GENERATED by scripts/sync_sidplayfp_filtermaps.sh - do not edit.\n')
    f.write(f' * Source: {origin}\n')
    f.write(' * Author -> recommended 6581 filter values (sidplayfp autofilter).\n')
    f.write(' * Strings are latin-1 as upstream writes them (SID info strings\n')
    f.write(' * are latin-1 too, so lookups compare byte-for-byte). */\n')
    f.write('#ifndef SID_FILTER_MAPS_H\n#define SID_FILTER_MAPS_H\n\n')
    f.write('typedef struct { const char* author; double value; } SidFilterEntry;\n\n')
    for cname, entries in (('kSidFilterRangeMap', ranges), ('kSidFilterCurveMap', curves)):
        f.write(f'static const SidFilterEntry {cname}[] = {{\n')
        for a, v in entries:
            f.write(f'    {{ "{a}", {v} }},\n')
        f.write('};\n')
        f.write(f'static const int {cname}Count = (int)(sizeof({cname}) / sizeof({cname}[0]));\n\n')
    f.write('#endif /* SID_FILTER_MAPS_H */\n')
print(f'wrote {out}: {len(ranges)} range entries, {len(curves)} curve entries')
PY
